package com.hida.model;

import javax.persistence.Entity;
import javax.persistence.Transient;

/**
 * An Pid generated by AutoIdGenerator
 *
 * @author lruffin
 */
@Entity
public class AutoId extends Pid {

    @Transient
    private String TokenMap;

    /**
     * No-arg constructor used by Hibernate
     */
    public AutoId() {

    }

    /**
     * Copy constructor
     *
     * @param id An object with values to copy
     */
    public AutoId(AutoId id) {
        super(id);
        this.TokenMap = id.getTokenMap();
    }

    /**
     * Recommended constructor used to create new Pids
     *
     * @param prefix A sequence of characters that appear in the beginning of
     * PIDs
     * @param baseMap An array of integers that contain the indices described by
     * tokenMap
     * @param tokenMap A sequence of characters all possible characters a PID
     * can contain
     */
    public AutoId(String prefix, int[] baseMap, String tokenMap) {
        super(baseMap, prefix);
        this.TokenMap = tokenMap;
    }

    /**
     * Increments a value of a PID. If the maximum limit is reached the values
     * will wrap around.
     *
     * @return true if the id has been successfully incremented
     */
    @Override
    public boolean incrementId() {
        int range = this.getBaseMap().length - 1;

        boolean overflow = true;
        for (int k = 0; k < this.getBaseMap().length && overflow; k++) {
            // record value of current index
            int value = this.getBaseMap()[range - k];

            if (value == TokenMap.length() - 1) {
                this.getBaseMap()[range - k] = 0;
            }
            else {
                this.getBaseMap()[range - k]++;
                overflow = false;
            }
        }

        return !overflow;
    }

    @Override
    public String toString() {
        return getName();
    }

    /**
     * Creates the name of the id based on the indices contained in the BaseMap
     * and the characters in the TokenMap
     *
     * @return The Name of the Pid
     */
    @Override
    public String getName() {
        Name = "";
        for (int i = 0; i < this.getBaseMap().length; i++) {
            Name += TokenMap.charAt(this.getBaseMap()[i]);
        }
        return this.getPrefix() + Name;
    }

    public String getTokenMap() {
        return TokenMap;
    }

    public void setTokenMap(String TokenMap) {
        this.TokenMap = TokenMap;
    }

}
